
openapi: 3.0.0
info:
  title: 'Validacion'
  version: 1.0.0
servers:
  - url: 'http://remoto.com'
    description: 'Prod server'
  - url: 'http://controles.test:8000'
    description: 'Dev server'
paths:
  /validaciones:
    post:
      description: Crear una nueva validacion
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Validacion'
      responses:
        200:
          description: Exito al crear la validacion

components:
  schemas:
    Validacion:
      $ref: './models/validacion.model.yaml#/components/schemas/Validacion'

